### ISSUE TITLE
Question regarding licensing

### ISSUE THREAD

**Issue by flaw600** [austinzheng/swift-2048#16]
The source code states that all rights are reserved, which to me means closed-source, but the LICENSE file says that this is under MIT. Just for clarification, which license, if any, is being used?

**Comment by austinzheng** [comment]
The project is licensed under the terms of the MIT license. The "all rights reserved" is Xcode boilerplate and not intended to contradict the terms of and rights granted by the MIT licnese. Since its existence introduces ambiguity, I will remove it as soon as possible.

**Comment by flaw600** [comment]
Yeah, I figured that it was boilerplate but I just wanted to make sure so that I didn't infringe on any copyright. As an additional question, is this sort of tinkering with the original 2048 game permissible? I understand that this implementation is a fork of a clean-room project which, to my understanding, doesn't violate any rights per se but I just want to check all my bases.

**Comment by flaw600** [comment]
I think I just answered my own question as 2048 is open-sourced under MIT. Never mind. I'll leave this open to close at your leisure.

**Comment by austinzheng** [comment]
Thanks for asking. IANAL, and you mentioned that 2048 is MIT, but as far as I am aware game concepts cannot be copyrighted, only specific assets, and games are ineligible for patent protection. Wikipedia is not a source for legal advice either, but the fact that they have an article on the topic (https://en.wikipedia.org/wiki/Video_game_clone#Legal_aspects) indicates that the question is, at least, of widespread interest.

Please let me know if you have any more questions, and thanks for dropping by!
